name: Cross-Service Feature
description: A feature requiring changes across multiple Scry services
labels: ["codex"]
body:
  - type: markdown
    attributes:
      value: |
        Agent selection:
        - Default: `codex` (Codex 5.3)
        - Add the `claude` label to run Claude instead

  - type: input
    id: title
    attributes:
      label: Feature Title
      placeholder: e.g., Add health check endpoint across services
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to change and why
      placeholder: Describe the feature and the motivation behind it
    validations:
      required: true

  - type: checkboxes
    id: services
    attributes:
      label: Affected Services
      description: Select all services that need changes (dependency labels are auto-added). If a new service label is not listed yet, add it manually on the issue.
      options:
        - label: "scry-ops"
        - label: "upload-service"
        - label: "build-processing"
        - label: "cdn-service"
        - label: "dashboard"
        - label: "scry-node"
        - label: "sbcov"
        - label: "search-api"
        - label: "landing-page"
        - label: "scry-link"

  - type: textarea
    id: shared-interfaces
    attributes:
      label: Shared Interface Changes
      description: API contracts, Firestore schemas, R2 paths, or data formats that span services
      placeholder: |
        e.g.,
        - New field `healthStatus` on Firestore `builds` collection
        - New endpoint GET /health on upload-service and cdn-service

  - type: textarea
    id: per-service
    attributes:
      label: Per-Service Changes
      description: Expected changes in each affected service
      placeholder: |
        e.g.,
        - upload-service: Add GET /health endpoint returning uptime and R2 connectivity
        - cdn-service: Add GET /health endpoint returning uptime and KV connectivity
